[package]
name = "daisneon"
version = "0.1.0"
authors = ["Paul deGrandis <paul.degrandis@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "daisneon"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.20"

[dependencies]
neon = "0.1.20"
itertools = "0.6.5"
